### ISSUE TITLE
Does support individual macros for each controller connected?

### ISSUE THREAD

**Issue by Trihy** [TRARS/CustomMacroExtension#1]
Hi. One limitation of ds4windows, was it replicates the macro actions on all controllers connected. So you have a macro of ie. A+B+UP for controller 1, but will be replicated on all controllers when presssing the button on controller 1.

Does yor build of DS4W have individual macro for each controller?

Thanks.

**Comment by TRARS** [comment]
It can be addressed using this approach: when the Ex3 switch is opened in MacroWindow, obtain the controller index in the UpdateState method of MacroExtension by reading the Ind property.
```
        public override void UpdateState()
        {
            if (MainGate.Enable is false) { return; }

            MacroForController0(Ind == 0);
            MacroForController1(Ind == 1);
        }

        void MacroForController0(bool canExecute)
        {
            if (!canExecute) { return; }
        }

        void MacroForController1(bool canExecute)
        {
            if (!canExecute) { return; }
        }
```
